package com.example.sqlmcpchatopenrouter.chat;

import java.util.List;

import org.springframework.util.StringUtils;

/** Stable response returned by both the JSON and SSE chat endpoints. */
public record ChatResponse(String conversationId, String model, boolean fallbackUsed, Status status, String message,
        List<String> columns, List<List<String>> rows, boolean usedDatabaseTools, boolean partialResults,
        String dataNotes, String followUpQuestion) {

    public ChatResponse {
        conversationId = safe(conversationId);
        model = safe(model);
        status = status == null ? Status.ANSWER : status;
        message = safe(message);
        columns = columns == null ? List.of() : List.copyOf(columns);
        rows = rows == null ? List.of()
                : rows.stream().map(row -> row == null ? List.<String>of() : List.copyOf(row)).toList();
        dataNotes = safe(dataNotes);
        followUpQuestion = safe(followUpQuestion);
    }

    public static ChatResponse from(String conversationId, String model, boolean fallbackUsed, ModelAnswer answer,
            boolean usedDatabaseTools) {
        ModelAnswer safeAnswer = answer == null ? ModelAnswer.empty() : answer;
        return new ChatResponse(conversationId, model, fallbackUsed, safeAnswer.resolvedStatus(), safeAnswer.answer(),
                safeAnswer.columns(), safeAnswer.rows(), usedDatabaseTools, safeAnswer.partialResults(),
                safeAnswer.dataNotes(), safeAnswer.followUpQuestion());
    }

    public enum Status {
        ANSWER,
        CLARIFICATION,
        EMPTY,
        PARTIAL,
        ERROR
    }

    /** The portion of the response generated by the model's JSON schema. */
    public record ModelAnswer(Status status, String answer, List<String> columns, List<List<String>> rows,
            Boolean partialResults, String dataNotes, String followUpQuestion) {

        public ModelAnswer {
            answer = safe(answer);
            columns = columns == null ? List.of() : List.copyOf(columns);
            rows = rows == null ? List.of()
                    : rows.stream().map(row -> row == null ? List.<String>of() : List.copyOf(row)).toList();
            partialResults = partialResults != null && partialResults;
            dataNotes = safe(dataNotes);
            followUpQuestion = safe(followUpQuestion);
        }

        static ModelAnswer empty() {
            return new ModelAnswer(Status.ERROR, "", List.of(), List.of(), false, "", "");
        }

        Status resolvedStatus() {
            if (status != null) {
                return status;
            }
            if (StringUtils.hasText(followUpQuestion)) {
                return Status.CLARIFICATION;
            }
            return partialResults ? Status.PARTIAL : Status.ANSWER;
        }
    }

    private static String safe(Object value) {
        return value == null ? "" : value.toString();
    }
}
